apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service-1
  template:
    metadata:
      labels:
        app: api-service-1
    spec:
      containers:
      - name: api-service-1
        image: api-service-1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-1
spec:
  selector:
    app: api-service-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP