apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service-2
  template:
    metadata:
      labels:
        app: api-service-2
    spec:
      containers:
      - name: api-service-2
        image: api-service-2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-2
spec:
  selector:
    app: api-service-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP