# Use official Node.js image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install --only=production

# Copy application source code
COPY . .

# Expose port
EXPOSE 3002

# Run the app
CMD ["node", "--require", "./instrumentation.js", "index.js"]